#ifndef GUI_MENU_COORD_H
#define GUI_MENU_COORD_H

#include "../gui_constants.h"

#define BUTTONS_OX (MENU_ORIGIN_X + (MENU_WIDTH/16))
#define BUTTONS_W (MENU_WIDTH - (MENU_WIDTH/8))

#define PLAYER_TYPE_BUTTON_OX BUTTONS_OX
#define PLAYER_TYPE_BUTTON_OY (MENU_ORIGIN_Y + (MENU_WIDTH/16))
#define PLAYER_TYPE_BUTTON_OY2 (PLAYER_TYPE_BUTTON_OY*4)
#define PLAYER_TYPE_BUTTON_W BUTTONS_W
#define PLAYER_TYPE_BUTTON_H (MENU_HEIGHT/16)
    
#define LAUNCH_BUTTON_OX BUTTONS_OX
#define LAUNCH_BUTTON_OY (PLAYER_TYPE_BUTTON_OY*8)
#define LAUNCH_BUTTON_W BUTTONS_W
#define LAUNCH_BUTTON_H (MENU_HEIGHT/8)

#endif
