#ifndef GUI_MENU_COORD_H
#define GUI_MENU_COORD_H
#include "../gui_constants.h"

#define BUTTONS_OX (MENU_ORIGIN_X + (MENU_WIDTH/16))
#define BUTTONS_W (MENU_WIDTH - (MENU_WIDTH/8))

// Zone de message en haut
#define MESSAGE_OX MENU_ORIGIN_X
#define MESSAGE_OY MENU_ORIGIN_Y
#define MESSAGE_W MENU_WIDTH
#define MESSAGE_H (MENU_HEIGHT/8)

// Bouton "Reprise de coup"
#define UNDO_BUTTON_OX BUTTONS_OX
#define UNDO_BUTTON_OY (MENU_ORIGIN_Y + MESSAGE_H + 10)
#define UNDO_BUTTON_W BUTTONS_W
#define UNDO_BUTTON_H (MENU_HEIGHT/16)

// Boutons type de joueur
#define PLAYER_TYPE_BUTTON_OX BUTTONS_OX
#define PLAYER_TYPE_BUTTON_OY (UNDO_BUTTON_OY + UNDO_BUTTON_H + 20)
#define PLAYER_TYPE_BUTTON_OY2 (PLAYER_TYPE_BUTTON_OY + UNDO_BUTTON_H + 20)
#define PLAYER_TYPE_BUTTON_W BUTTONS_W
#define PLAYER_TYPE_BUTTON_H (MENU_HEIGHT/16)
    
// Bouton lancer partie
#define LAUNCH_BUTTON_OX BUTTONS_OX
#define LAUNCH_BUTTON_OY (PLAYER_TYPE_BUTTON_OY2 + PLAYER_TYPE_BUTTON_H + 40)
#define LAUNCH_BUTTON_W BUTTONS_W
#define LAUNCH_BUTTON_H (MENU_HEIGHT/8)

#endif